directories:
  output: dist
  buildResources: build
appId: com.playoptix.tds8bridge
productName: TDS-8 Bridge
files:
  - filter:
      - '**/*'
extraResources:
  - from: ../TDS-8_Bridge/resources/tds8-bridge
    to: tds8-bridge
    filter:
      - '**/*'
      - '!node_modules/.bin'
      - '!node_modules/electron'
asar: true
win:
  icon: ../tds8-bridge/assets/icon-white.png
  target:
    - portable
mac:
  icon: ../tds8-bridge/assets/icon-white.png
  category: public.app-category.music
electronVersion: 28.3.3
